### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TrevorVV**
added the install command for the Arch linux package manager, pacman.

### CODE REVIEW

**Comment by lordadamson** [comment]
Hi @TrevorVV and welcome! :D 
Does that command install all the necessary qt5 lib packages?
have you tested this on your machine to make sure that there are no other dependencies for the project that needs to be installed?

**Comment by TrevorVV** [comment]
Hey thanks, and it will prompt you on install what packages you want, such
as this:

[trev@arch ~]$ sudo pacman -S qt5
:: There are 36 members in group qt5:
:: Repository extra
   1) qt5-3d  2) qt5-base  3) qt5-canvas3d  4) qt5-charts
   5) qt5-connectivity  6) qt5-datavis3d  7) qt5-declarative
   8) qt5-doc  9) qt5-examples  10) qt5-gamepad
   11) qt5-graphicaleffects  12) qt5-imageformats  13) qt5-location
   14) qt5-multimedia  15) qt5-networkauth  16) qt5-quickcontrols
   17) qt5-quickcontrols2  18) qt5-remoteobjects  19) qt5-script
   20) qt5-scxml  21) qt5-sensors  22) qt5-serialbus
   23) qt5-serialport  24) qt5-speech  25) qt5-svg  26) qt5-tools
   27) qt5-translations  28) qt5-virtualkeyboard  29) qt5-wayland
   30) qt5-webchannel  31) qt5-webengine  32) qt5-webkit
   33) qt5-websockets  34) qt5-webview  35) qt5-x11extras
   36) qt5-xmlpatterns

Enter a selection (default=all):

**Comment by lordadamson** [comment]
Alright then cool. Please be sure to use the back-tick like so:
```
`sudo pacman -S qt5`
```
So that it would rendered as code. Thanks in advance :D

**Comment by TrevorVV** [comment]
sounds good, sorry I'm brand new to GitHub but excited to be here!

**Comment by TrevorVV** [comment]
did that work?

**Comment by lordadamson** [comment]
Yes, it did! :D Welcome and congratulations on your first pull request.

**Comment by TrevorVV** [comment]
Haha sweet thanks!

**Pull request merged**
